### ISSUE TITLE
reproducing FRSKD issue

### ISSUE THREAD

**Issue by bkw0622** [winycg/Self-KD-Lib#2]
Hi!
I am grateful for your good work.
Now I'm learning FRSKD with your code, but the performance is about 62.xx, which is different from what is specified in github. 
How can I fix this error?
(The code is nothing changed)

Thanks a lot!!

**Comment by winycg** [comment]
Hi, does the result use ResNet-18 as the backbone? This result seems abnormal. I will run this code again and tell you new result.

**Comment by winycg** [comment]
Hi, thanks for pointing out this bug. The problem is that we use imagenet version's ResNet-18 as the backbone for FRSKD.Now I have fixed this bug, and re-run FRSKD and achieves 76.6% top-1 accuracy on CIFAR-100. Since the architecture of BiFPN in FRSKD can be more complexed, you may tune the hyper-parameters to pursue better performance.

**Comment by yhaochen0617** [comment]
hihi, thank you for sharing your work~
Could you share your train_log of ImageNet (MixSKD and mixup baseline) to me ?
My email is yhao.chen0617@gmail.com. Thank you very much.

**Comment by winycg** [comment]
@yhaochen0617 Hi, I sent the train_log of MixSKD on ImageNet to you. The mixup baseline log is unavailable at hand.
Thx!

**Comment by bkw0622** [comment]
Thanks for the quick reply!

**Comment by winycg** [comment]
@bkw0622 By the way, the result of FRSKD is borrowed from their original paper, and I did not reproduce this result. Besides, other results are reproduced by ours. I will modify it.

**Comment by yhaochen0617** [comment]
hihi  你好，mixskd imagenet你有跑过100epoch的吗?
我在这个codebase下面跑了resnet50 + mixup的baseline,
100epoch时点数只有76.4左右，正确的点数应该是77.1，我用的超参是8卡batch_size=256， init_lr = 0.1,
weight_decay=1e-4

winycg ***@***.***> 于2022年12月4日周日 13:58写道：
